name: Nextjs Test & Build
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      NEXT_PUBLIC_CLERK_FRONTEND_API: clerk.e4t11.3y1c1.lcl.dev
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install

    - name: Check out repository code
      uses: actions/checkout@v2
    # Necessary to generate the coverage report.
    - name: Install dependency
      run: yarn install
    - name: Tests
      run: yarn test:ci
    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
      with:
        branches: develop


    - run: yarn test
    - run: yarn build
